Repository OpenRakis/Spice86, pull requests merged in 2023-07, with the labels that each got.

#366 Migration/avalonia v11
  src/Spice86/App.axaml
  src/Spice86/App.axaml.cs
  src/Spice86/Program.cs
  src/Spice86/Spice86.csproj
  src/Spice86/Startup.cs
  src/Spice86/UserControls/PaletteUserControl.axaml
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/VideoBufferViewModel.cs
  src/Spice86/Views/DebugWindow.axaml.cs
  src/Spice86/Views/MainWindow.axaml
  src/Spice86/Views/MainWindow.axaml.cs
  src/Spice86/Views/PaletteWindow.axaml.cs
  src/Spice86/Views/PerformanceWindow.axaml
  src/Spice86/Views/PerformanceWindow.axaml.cs
  src/Spice86/Views/VideoBufferView.axaml
  src/Spice86/Views/VideoBufferView.axaml.cs
Labels: UI, refactoring, migration

#362 Breakpoints cleanup
  src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs
  src/Spice86.Core/Emulator/Memory/Memory.cs
  src/Spice86.Core/Emulator/VM/Breakpoint/AddressBreakPoint.cs
  src/Spice86.Core/Emulator/VM/Breakpoint/AddressRangeBreakPoint.cs
  src/Spice86.Core/Emulator/VM/Breakpoint/BreakPoint.cs
  src/Spice86.Core/Emulator/VM/Breakpoint/BreakPointHolder.cs
  src/Spice86.Core/Emulator/VM/Breakpoint/UnconditionalBreakPoint.cs
  src/Spice86.Tests/MachineTest.cs
Labels: performance, reverse engineering, refactoring

#369 Rework Memory class
  src/Spice86.Core/Emulator/CPU/CPU.cs
  src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16.cs
  src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16Or32.cs
  src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions32.cs
  src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions8.cs
  src/Spice86.Core/Emulator/CPU/ModRM.cs
  src/Spice86.Core/Emulator/CPU/Stack.cs
  src/Spice86.Core/Emulator/Callback/CallbackHandler.cs
  src/Spice86.Core/Emulator/Function/FunctionHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandMemoryHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/Ems/ExpandedMemoryManager.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseDriver.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs
  src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeLoader.cs
  src/Spice86.Core/Emulator/LoadableFile/Dos/PspGenerator.cs
  src/Spice86.Core/Emulator/Memory/IByteReaderWriter.cs
  src/Spice86.Core/Emulator/Memory/Indexer/IIndexed.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt16Indexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt32Indexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt8Indexer.cs
  src/Spice86.Core/Emulator/Memory/Memory.cs
  src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs
  src/Spice86.Core/Emulator/ReverseEngineer/MemoryBasedDataStructure.cs
  src/Spice86.Tests/MachineTest.cs
  src/Spice86.Tests/MainMemoryTest.cs
  src/Spice86/Views/PerformanceWindow.axaml
Labels: reverse engineering, refactoring, code generation

#376 fix: MainWindow not closing (Avaloniav11)
  src/Spice86/App.axaml.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/Views/MainWindow.axaml.cs
Labels: UI, bugfix

#370 Separate Interrupts and Callbacks. Make mouse CALL instruction explicit in memory
  src/Spice86.Core/Emulator/CPU/CPU.cs
  src/Spice86.Core/Emulator/CPU/InterruptVectorTable.cs
  src/Spice86.Core/Emulator/Callback/CallbackHandler.cs
  src/Spice86.Core/Emulator/Callback/ICallback.cs
  src/Spice86.Core/Emulator/Callback/IndexBasedDispatcher.cs
  src/Spice86.Core/Emulator/Function/Dump/ExecutionFlowDumper.cs
  src/Spice86.Core/Emulator/Function/Dump/RecorderDataWriter.cs
  src/Spice86.Core/Emulator/Function/ExecutionFlowRecorder.cs
  src/Spice86.Core/Emulator/Function/FunctionHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Bios/BiosEquipmentDeterminationInt11Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Bios/SystemBiosInt15Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/Callback/Callback.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/Callback/CallbackHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/Callback/ICallback.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/Callback/UnhandledCallbackException.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/IndexBasedDispatcher/IRunnable.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/IndexBasedDispatcher/IndexBasedDispatcher.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/IndexBasedDispatcher/RunnableAction.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryAsmWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt20Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt2fHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/Ems/ExpandedMemoryManager.cs
  src/Spice86.Core/Emulator/InterruptHandlers/IInterruptHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/BiosKeyboardInt9Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/KeyboardInt16Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/BiosMouseInt74Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/CustomMouseInt90Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/IAsmUserRoutineHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/IMouseDriver.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseDriver.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseInt33Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/InterruptHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/InterruptInstaller.cs
  src/Spice86.Core/Emulator/InterruptHandlers/SystemClock/SystemClockInt1AHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Timer/TimerInt8Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/IVideoInt10Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaBios.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs
  src/Spice86.Core/Emulator/Memory/Indexer/ByteArrayBasedIndexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/ByteArrayByteReaderWriter.cs
  src/Spice86.Core/Emulator/Memory/Indexer/IIndexed.cs
  src/Spice86.Core/Emulator/Memory/Indexer/OffsetSegmentIndexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt16Indexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt32Indexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt8Indexer.cs
  src/Spice86.Core/Emulator/Memory/Memory.cs
  src/Spice86.Core/Emulator/OperatingSystem/Dos.cs
  src/Spice86.Core/Emulator/ProgramExecutor.cs
  src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs
  src/Spice86.Core/Emulator/VM/Machine.cs
  src/Spice86.Core/Spice86.Core.csproj
  src/Spice86.Shared/Emulator/Memory/SegmentedAddress.cs
  src/Spice86.Tests/CSharpOverrideHelperTest.cs
  src/Spice86.Tests/MachineTest.cs
Labels: input, hardware, callback, refactoring, code generation, bugfix

#378 Rework memory indexers and MemoryBasedDataStructure
  src/Spice86.Core/Emulator/CPU/InterruptVectorTable.cs
  src/Spice86.Core/Emulator/Devices/Video/VideoFunctionalityInfo.cs
  src/Spice86.Core/Emulator/Function/FunctionHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandMemoryHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/Callback/CallbackHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryAsmWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/BiosKeyboardBuffer.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/BiosKeyboardInt9Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/KeyboardInt16Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaBios.cs
  src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeFile.cs
  src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeLoader.cs
  src/Spice86.Core/Emulator/Memory/Indexable/ByteArrayBasedIndexable.cs
  src/Spice86.Core/Emulator/Memory/Indexable/Indexable.cs
  src/Spice86.Core/Emulator/Memory/Indexer/ByteArrayBasedIndexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/IIndexed.cs
  src/Spice86.Core/Emulator/Memory/Indexer/Indexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/OffsetSegmentIndexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/SegmentedAddressIndexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/SegmentedAddressValueIndexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt16Indexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt32Indexer.cs
  src/Spice86.Core/Emulator/Memory/Indexer/UInt8Indexer.cs
  src/Spice86.Core/Emulator/Memory/Memory.cs
  src/Spice86.Core/Emulator/Memory/MemoryBreakpoints.cs
  src/Spice86.Core/Emulator/Memory/ReaderWriter/ByteArrayByteReaderWriter.cs
  src/Spice86.Core/Emulator/Memory/ReaderWriter/ByteReaderWriterWithBaseAddress.cs
  src/Spice86.Core/Emulator/Memory/ReaderWriter/IBaseAddressProvider.cs
  src/Spice86.Core/Emulator/Memory/ReaderWriter/IByteReaderWriter.cs
  src/Spice86.Core/Emulator/OperatingSystem/Structures/DosDiskTransferArea.cs
  src/Spice86.Core/Emulator/OperatingSystem/Structures/DosMemoryControlBlock.cs
  src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/AbstractMemoryBasedDataStructure.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/MemoryBasedArray.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/MemoryBasedArrayEnumerator.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/SegmentedAddressArray.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/UInt16Array.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/UInt32Array.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/UInt8Array.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructure.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructureWithCsBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructureWithDsBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructureWithEsBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructureWithFsBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructureWithGsBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructureWithSegmentRegisterBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/MemoryBasedDataStructureWithSsBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/MemoryBasedArray.cs
  src/Spice86.Core/Emulator/ReverseEngineer/MemoryBasedDataStructure.cs
  src/Spice86.Core/Emulator/ReverseEngineer/MemoryBasedDataStructureWithBaseAddress.cs
  src/Spice86.Core/Emulator/ReverseEngineer/MemoryBasedDataStructureWithBaseAddressProvider.cs
  src/Spice86.Core/Emulator/ReverseEngineer/UInt16Array.cs
  src/Spice86.Core/Emulator/ReverseEngineer/UInt8Array.cs
  src/Spice86.Core/Emulator/VM/MachineBreakpoints.cs
Labels: enhancement, memory, reverse engineering, refactoring

#386 Fix/clearer UI code
  src/Spice86.Shared/Interfaces/IGui.cs
  src/Spice86.Shared/Interfaces/IVideoBufferViewModel.cs
  src/Spice86/App.axaml
  src/Spice86/Converters/CountToBooleanConverter.cs
  src/Spice86/Spice86.csproj
  src/Spice86/UserControls/VideoBufferUserControl.axaml
  src/Spice86/UserControls/VideoBufferUserControl.axaml.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/VideoBufferViewModel.cs
  src/Spice86/Views/MainWindow.axaml
  src/Spice86/Views/MainWindow.axaml.cs
  src/Spice86/Views/PaletteWindow.axaml
  src/Spice86/app.manifest
Labels: refactoring

#388 Fix/faster startup
  src/Spice86/App.axaml
  src/Spice86/DependencyInjection/Composition.cs
  src/Spice86/DependencyInjection/LoggerServiceInjectionExtensions.cs
  src/Spice86/Program.cs
  src/Spice86/Spice86.csproj
  src/Spice86/Startup.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
Labels: performance, refactoring

#385 Uncouple INT74 and mouse driver implementations. Mouse driver now installs it's assembly code in ram itself and handles user routine call. INT74 calls the mouse driver when present.
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/InMemoryAddressSwitcher.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryAsmWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/RoutineInstall/AssemblyRoutineInstaller.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/RoutineInstall/IAssemblyRoutineWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/RoutineInstall/InterruptInstaller.cs
  src/Spice86.Core/Emulator/InterruptHandlers/IInterruptHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/BiosMouseInt74Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/IAsmUserRoutineHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/IMouseDriver.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseDriver.cs
  src/Spice86.Core/Emulator/InterruptHandlers/InterruptHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/InterruptInstaller.cs
  src/Spice86.Core/Emulator/VM/Machine.cs
Labels: refactoring
