Repository OpenRakis/Spice86, pull requests merged in 2024-07, with the labels that each got.

#750 Sync master branches
  src/Spice86.Core/Emulator/CPU/CPU.cs
  src/Spice86.Core/Emulator/CPU/Stack.cs
  src/Spice86.Core/Emulator/Function/CircularBuffer.cs
  src/Spice86.Core/Emulator/Function/Dump/GhidraSymbolsDumper.cs
  src/Spice86.Core/Emulator/Function/ExecutionFlowRecorder.cs
  src/Spice86.Core/Emulator/Function/FunctionHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbIo.cs
  src/Spice86.Core/Emulator/IOPorts/DefaultIOPortHandler.cs
  src/Spice86.Core/Emulator/IOPorts/IOPortDispatcher.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/Ems/ExpandedMemoryManager.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaBios.cs
  src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeLoader.cs
  src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
  src/Spice86.Core/Emulator/OperatingSystem/DosMemoryManager.cs
  src/Spice86.Core/Emulator/OperatingSystem/Structures/DosMemoryControlBlock.cs
  src/Spice86.Core/Emulator/ReverseEngineer/ArgumentFetcher.cs
  src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs
  src/Spice86.Logging/LoggerService.cs
  src/Spice86.Shared/Emulator/Memory/SegmentedAddress.cs
Labels: reverse engineering, DOS, CPU

#761 chore: update Nuget packages
  src/Bufdio.Spice86/Bufdio.Spice86.csproj
  src/Spice86.Core/Spice86.Core.csproj
  src/Spice86.Logging/Spice86.Logging.csproj
  src/Spice86.Shared/Spice86.Shared.csproj
  src/Spice86/Spice86.csproj
Labels: 3rd party

#762 Feature/debug on program error
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/Views/CfgCpuView.axaml
  src/Spice86/Views/MainWindow.axaml
Labels: reverse engineering, Dune, CFGCPU

#766 fix: stacktraces (removed Ben.Demistify package)
  src/Spice86.Core/CLI/CommandLineParser.cs
  src/Spice86.Core/Emulator/Function/Dump/ExecutionFlowDumper.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandMemoryHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandRegisterHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCustomCommandsHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbServer.cs
  src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
  src/Spice86.Core/Emulator/ProgramExecutor.cs
  src/Spice86.Core/Emulator/VM/EmulationLoop.cs
  src/Spice86.Core/Emulator/VM/PauseHandler.cs
  src/Spice86.Core/Spice86.Core.csproj
  src/Spice86/Spice86.csproj
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/ViewModelBaseWithErrorDialog.cs
Labels: bugfix

#767 refactor: removed unused enricher Serilog.Exceptions from logger
  src/Spice86.Logging/LoggerService.cs
  src/Spice86.Logging/Spice86.Logging.csproj
  src/Spice86.Shared/Spice86.Shared.csproj
Labels: 3rd party

#765 fix: transform of 'C:????????.???' into '????????.???' fileSpec (PoP)
  src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
Labels: DOS, bugfix, regression

#744 Refactoring: UI TopLevel services and MainWindowViewModel injection
  src/Spice86.Core/CLI/CommandLineParser.cs
  src/Spice86.Core/CLI/ICommandLineParser.cs
  src/Spice86/App.axaml.cs
  src/Spice86/DependencyInjection/ServiceCollectionExtensions.cs
  src/Spice86/Infrastructure/HostStorageProvider.cs
  src/Spice86/Infrastructure/IHostStorageProvider.cs
  src/Spice86/Interfaces/IPauseStatus.cs
  src/Spice86/MemoryWrappers/CodeMemoryStream.cs
  src/Spice86/MemoryWrappers/DataMemoryDocument.cs
  src/Spice86/Program.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/Views/MainWindow.axaml
Labels: UI, refactoring

#772 Feature/structure viewer
  src/Spice86.Core/CLI/Configuration.cs
  src/Spice86.Core/Emulator/Function/IOverrideSupplier.cs
  src/Spice86.Shared/Emulator/Memory/SegmentedAddress.cs
  src/Spice86/Converters/SegmentedAddressConverter.cs
  src/Spice86/DataTemplates/DataTemplateProvider.cs
  src/Spice86/DependencyInjection/ServiceCollectionExtensions.cs
  src/Spice86/Infrastructure/FilePoller.cs
  src/Spice86/Infrastructure/StructureViewModelFactory.cs
  src/Spice86/Interfaces/IStructureViewModelFactory.cs
  src/Spice86/Models/AddressChangedMessage.cs
  src/Spice86/Spice86.csproj
  src/Spice86/Styles/Spice86.axaml
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/StructureViewModel.cs
  src/Spice86/Views/MemoryView.axaml
  src/Spice86/Views/MemoryView.axaml.cs
  src/Spice86/Views/StructureView.axaml
  src/Spice86/Views/StructureView.axaml.cs
Labels: UI, memory, reverse engineering

#770 refactor: Inversion of control for all dependencies between classes in the UI
  src/Spice86/DependencyInjection/ServiceCollectionExtensions.cs
  src/Spice86/Interfaces/IPauseStatus.cs
  src/Spice86/Program.cs
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/CpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/Messages/AddViewModelMessage.cs
  src/Spice86/ViewModels/Messages/PauseStatusMessage.cs
  src/Spice86/ViewModels/Messages/RemoveViewModelMessage.cs
  src/Spice86/ViewModels/PaletteViewModel.cs
  src/Spice86/ViewModels/PerformanceViewModel.cs
Labels: UI, refactoring, dependency injection

#780 Revert "refactor: Inversion of control for all dependencies between c…
  src/Spice86/DependencyInjection/ServiceCollectionExtensions.cs
  src/Spice86/Interfaces/IPauseStatus.cs
  src/Spice86/Program.cs
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/CpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/Messages/AddViewModelMessage.cs
  src/Spice86/ViewModels/Messages/PauseStatusMessage.cs
  src/Spice86/ViewModels/Messages/RemoveViewModelMessage.cs
  src/Spice86/ViewModels/PaletteViewModel.cs
  src/Spice86/ViewModels/PerformanceViewModel.cs
Labels: UI

#793 chore: update Nuget packages (Avalonia, Serilog)
  src/Spice86.Core/Spice86.Core.csproj
  src/Spice86.Logging/Spice86.Logging.csproj
  src/Spice86.Shared/Spice86.Shared.csproj
  src/Spice86/Spice86.csproj
Labels: 3rd party

#794 Fix: dashes in passed cmdline args
  src/Spice86.Core/CLI/CommandLineParser.cs
Labels: bugfix, 3rd party

#796 Feature: emulator logs to file
  src/Spice86.Logging/LoggerService.cs
  src/Spice86.Logging/Spice86.Logging.csproj
Labels: reverse engineering

#792 Pause handling
  src/Spice86.Core/Emulator/Devices/DirectMemoryAccess/DmaController.cs
  src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlaster.cs
  src/Spice86.Core/Emulator/Devices/Sound/Midi/GeneralMidiDevice.cs
  src/Spice86.Core/Emulator/Devices/Sound/Midi/MT32/Mt32MidiDevice.cs
  src/Spice86.Core/Emulator/Devices/Sound/Midi/MT32/Mt32Player.cs
  src/Spice86.Core/Emulator/Devices/Sound/Midi/Midi.cs
  src/Spice86.Core/Emulator/Devices/Sound/SoftwareMixer.cs
  src/Spice86.Core/Emulator/Devices/Sound/Ymf262Emu/OPL3FM.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbServer.cs
  src/Spice86.Core/Emulator/IProgramExecutor.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt28Handler.cs
  src/Spice86.Core/Emulator/OperatingSystem/Dos.cs
  src/Spice86.Core/Emulator/ProgramExecutor.cs
  src/Spice86.Core/Emulator/VM/EmulationLoop.cs
  src/Spice86.Core/Emulator/VM/IPauseHandler.cs
  src/Spice86.Core/Emulator/VM/Machine.cs
  src/Spice86.Core/Emulator/VM/MachineBreakpoints.cs
  src/Spice86.Core/Emulator/VM/PauseHandler.cs
  src/Spice86/Infrastructure/ProgramExecutorFactory.cs
  src/Spice86/Infrastructure/StructureViewModelFactory.cs
  src/Spice86/Program.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/StructureViewModel.cs
  tests/Spice86.Tests/CfgCpu/CfgNodeFeederTest.cs
  tests/Spice86.Tests/CfgCpu/InstructionsFeederTest.cs
  tests/Spice86.Tests/MachineCreator.cs
Labels: reverse engineering, refactoring
