Repository OpenRakis/Spice86, pull requests merged in 2024-10, with the labels that each got.

#873 feature: Internal Debugger: Start program paused
  src/Spice86.Core/CLI/Configuration.cs
  src/Spice86.Core/Emulator/ProgramExecutor.cs
Labels: feature request

#892 chore: update Nugets
  src/Bufdio.Spice86/Bufdio.Spice86.csproj
  src/Spice86.Core/Spice86.Core.csproj
  src/Spice86.Logging/Spice86.Logging.csproj
  src/Spice86.Shared/Spice86.Shared.csproj
  src/Spice86/Spice86.csproj
  tests/Spice86.Tests/Spice86.Tests.csproj
Labels: 3rd party

#905 chore: Nuget packages update
  src/Bufdio.Spice86/Bindings/PortAudio/NativeMethods.cs
  src/Bufdio.Spice86/Bindings/PortAudio/Structs/PaStreamParameters.cs
  src/Bufdio.Spice86/Bufdio.Spice86.csproj
  src/Bufdio.Spice86/Engines/PortAudioEngine.cs
  src/Bufdio.Spice86/Exceptions/PortAudioException.cs
  src/Bufdio.Spice86/PortAudioLib.cs
  src/Bufdio.Spice86/Utilities/Extensions/PortAudioExtensions.cs
  src/Directory.Build.props
  src/Spice86.Core/Spice86.Core.csproj
  src/Spice86.Logging/Spice86.Logging.csproj
  src/Spice86.Shared/Spice86.Shared.csproj
  src/Spice86/Spice86.csproj
  src/Spice86/Views/CpuView.axaml
  src/Spice86/Views/MidiView.axaml
  tests/Spice86.Tests/CSharpOverrideHelperTest.cs
  tests/Spice86.Tests/CfgCpu/CfgNodeFeederTest.cs
  tests/Spice86.Tests/CfgCpu/InstructionDiscriminatorTest.cs
  tests/Spice86.Tests/CfgCpu/InstructionsFeederTest.cs
  tests/Spice86.Tests/CfgCpu/ModRm/ModRmHelper.cs
  tests/Spice86.Tests/CfgCpu/ModRm/ModRmParserTest.cs
  tests/Spice86.Tests/Dos/DosFileManagerTests.cs
  tests/Spice86.Tests/MachineTest.cs
  tests/Spice86.Tests/MemoryBasedDataStructureTest.cs
  tests/Spice86.Tests/PicTests.cs
  tests/Spice86.Tests/Spice86.Tests.csproj
  tests/Spice86.Tests/Spice86Creator.cs
Labels: 3rd party

#906 Sync minor additions
  README.md
  doc/BaK.png
  src/Spice86.Core/Emulator/Devices/Video/VgaIoPortHandler.cs
  src/Spice86.Core/Emulator/ReverseEngineer/ArgumentFetcher.cs
  src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs
Labels: reverse engineering
