Repository OpenRakis/Spice86, pull requests merged in 2024-09, with the labels that each got.

#815 Feature: Internal debugger step into and memory search.
  src/Spice86.Core/Emulator/CPU/Stack.cs
  src/Spice86.Core/Emulator/Devices/Timer/Counter.cs
  src/Spice86.Core/Emulator/Devices/Timer/CounterActivator.cs
  src/Spice86.Core/Emulator/Devices/Timer/CounterConfiguratorFactory.cs
  src/Spice86.Core/Emulator/Devices/Timer/CyclesCounterActivator.cs
  src/Spice86.Core/Emulator/Devices/Timer/TimeCounterActivator.cs
  src/Spice86.Core/Emulator/Devices/Timer/Timer.cs
  src/Spice86.Core/Emulator/VM/Breakpoint/BreakPointType.cs
  src/Spice86.Shared/Utils/ConvertUtils.cs
  src/Spice86/App.axaml
  src/Spice86/Assets/ControlThemes.axaml
  src/Spice86/Controls/GroupBox.cs
  src/Spice86/Controls/HotKeyTabItem.cs
  src/Spice86/Controls/StatusBar.cs
  src/Spice86/Controls/StatusBarItem.cs
  src/Spice86/Converters/InvalidNumberToQuestionMarkConverter.cs
  src/Spice86/MemoryWrappers/MemoryReadOnlyBitRangeUnion.cs
  src/Spice86/Models/Debugging/CpuInstructionInfo.cs
  src/Spice86/Spice86.csproj
  src/Spice86/Spice86DependencyInjection.cs
  src/Spice86/Styles/Spice86.axaml
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/CpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/PaletteViewModel.cs
  src/Spice86/ViewModels/PerformanceViewModel.cs
  src/Spice86/Views/CpuView.axaml
  src/Spice86/Views/DebugWindow.axaml
  src/Spice86/Views/DisassemblyView.axaml
  src/Spice86/Views/MainWindow.axaml
  src/Spice86/Views/MemoryView.axaml
  src/Spice86/Views/MidiView.axaml
  src/Spice86/Views/SoftwareMixerView.axaml
Labels: UI, reverse engineering

#855 Fix CfgCpu messing up graph on external interruptions. Make interrupt vector table a memory based array.
  src/Spice86.Core/Emulator/CPU/CfgCpu/CfgCpu.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/ExecutionContextManager.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CfgNodeFeeder.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CurrentInstructions.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/DiscriminatorReducer.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/IInstructionReplacer.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/InstructionReplacer.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/InstructionReplacerRegistry.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/InstructionsFeeder.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/PreviousInstructions.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Linker/ExecutionContext.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Linker/NodeLinker.cs
  src/Spice86.Core/Emulator/CPU/InterruptVectorTable.cs
  src/Spice86.Core/Emulator/ProgramExecutor.cs
  src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/MemoryBasedArray.cs
  src/Spice86.Core/Emulator/VM/EmulationLoop.cs
  src/Spice86/Spice86DependencyInjection.cs
  tests/Spice86.Tests/CfgCpu/CfgNodeFeederTest.cs
  tests/Spice86.Tests/CfgCpu/InstructionsFeederTest.cs
Labels: 32 bit, 16 bit, Dune, bugfix, CFGCPU

#822 chore: upgraded Avalonia, tests SDKs, Roslynator, Avalonia 3rd party controls and styles
  src/Bufdio.Spice86/Bufdio.Spice86.csproj
  src/Spice86.Core/Spice86.Core.csproj
  src/Spice86.Logging/Spice86.Logging.csproj
  src/Spice86.Shared/Spice86.Shared.csproj
  src/Spice86/Spice86.csproj
  tests/Spice86.Tests/Spice86.Tests.csproj
Labels: 3rd party
