Repository OpenRakis/Spice86, pull requests merged in 2025-03, with the labels that each got.

#1074 fix: semi-UI freeze
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/PerformanceViewModel.cs
Labels: UI, bugfix

#998 Internal Debugger: All breakpoints can be created (including I/O ports breakpoints) and edited + CPU Stack View
  src/Spice86/Converters/HexadecimalStringToNumberConverter.cs
  src/Spice86/Converters/InstructionToStringConverter.cs
  src/Spice86/Converters/SegmentedAddressConverter.cs
  src/Spice86/Converters/SegmentedAddressToLinearAddressConverter.cs
  src/Spice86/Converters/UintToAsciiConverter.cs
  src/Spice86/MemoryWrappers/InstructionsDecoder.cs
  src/Spice86/Spice86DependencyInjection.cs
  src/Spice86/ViewModels/BreakpointTypeTabItemViewModel.cs
  src/Spice86/ViewModels/BreakpointViewModel.cs
  src/Spice86/ViewModels/BreakpointsViewModel.cs
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/CpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/StatusMessageViewModel.cs
  src/Spice86/ViewModels/ViewModelWithErrorDialog.cs
  src/Spice86/Views/BreakpointsView.axaml
  src/Spice86/Views/BreakpointsView.axaml.cs
  src/Spice86/Views/CpuView.axaml
  src/Spice86/Views/DebugWindow.axaml
  src/Spice86/Views/DisassemblyView.axaml
  src/Spice86/Views/DisassemblyView.axaml.cs
  src/Spice86/Views/MainWindow.axaml
  src/Spice86/Views/MemoryView.axaml
  src/Spice86/Views/StatusMessageView.axaml
Labels: UI, reverse engineering, Debugger

#1078 Fix pause events
  src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs
  src/Spice86.Core/Emulator/VM/IPauseHandler.cs
  src/Spice86.Core/Emulator/VM/PauseHandler.cs
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/CpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/PerformanceViewModel.cs
  src/Spice86/ViewModels/StructureViewModel.cs
Labels: bugfix

#1082 Segmented address improvements
  src/Spice86.Core/Emulator/CPU/CfgCpu/ExecutionContextManager.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CurrentInstructions.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/MemoryInstructionMatcher.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/SelfModifying/DiscriminatedNode.cs
  src/Spice86.Core/Emulator/CPU/CfgCpu/Parser/FieldReader/InstructionFieldReader.cs
  src/Spice86.Core/Emulator/Function/Dump/GhidraSymbolsDumper.cs
  src/Spice86.Core/Emulator/Function/ExecutionFlowRecorder.cs
  src/Spice86.Core/Emulator/Function/FunctionHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryAsmWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryWriter.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/BiosMouseInt74Handler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseDriver.cs
  src/Spice86.Core/Emulator/InterruptHandlers/InterruptHandler.cs
  src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs
  src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs
  src/Spice86.Shared/Emulator/Memory/SegmentedAddress.cs
  src/Spice86.Shared/Utils/ConvertUtils.cs
  src/Spice86/Messages/AddressChangedMessage.cs
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/StructureViewModel.cs
  src/Spice86/Views/StructureView.axaml.cs
Labels: enhancement, refactoring

#1079 Feature: hexa, decimal, and segmented address textbox compatibility everywhere
  src/Spice86.Core/Emulator/Devices/Sound/Midi/GeneralMidiDevice.cs
  src/Spice86.Core/Emulator/Devices/Sound/Midi/Midi.cs
  src/Spice86.Core/Emulator/Function/Dump/EmulatorStateSerializer.cs
  src/Spice86.Core/Emulator/Function/Dump/MemoryDataExporter.cs
  src/Spice86.Core/Emulator/Function/Dump/RecorderDataWriter.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandMemoryHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCommandRegisterHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbCustomCommandsHandler.cs
  src/Spice86.Core/Emulator/Gdb/GdbServer.cs
  src/Spice86.Core/Emulator/ProgramExecutor.cs
  src/Spice86.Shared/Utils/MemoryUtils.cs
  src/Spice86/Behaviors/UpdateBindingOnEnterBehavior.cs
  src/Spice86/Converters/AddressStringToLinearMemoryAddresssConverter.cs
  src/Spice86/Converters/BoolToBrushConverter.cs
  src/Spice86/Converters/HexadecimalStringToNumberConverter.cs
  src/Spice86/Converters/SegmentedAddressConverter.cs
  src/Spice86/Converters/SegmentedAddressToLinearAddressConverter.cs
  src/Spice86/Converters/UintToAsciiConverter.cs
  src/Spice86/MemoryWrappers/DataMemoryDocument.cs
  src/Spice86/MemoryWrappers/InstructionsDecoder.cs
  src/Spice86/Models/Debugging/FunctionInfo.cs
  src/Spice86/Models/Debugging/LinearMemoryAddress.cs
  src/Spice86/Spice86DependencyInjection.cs
  src/Spice86/ViewLocator.cs
  src/Spice86/ViewModels/BreakpointViewModel.cs
  src/Spice86/ViewModels/BreakpointsViewModel.cs
  src/Spice86/ViewModels/CfgCpuViewModel.cs
  src/Spice86/ViewModels/DebugWindowViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/StackMemoryViewModel.cs
  src/Spice86/ViewModels/ViewModelWithErrorDialog.cs
  src/Spice86/Views/BreakpointsView.axaml
  src/Spice86/Views/CfgCpuView.axaml
  src/Spice86/Views/CpuView.axaml
  src/Spice86/Views/DisassemblyView.axaml
  src/Spice86/Views/MainWindow.axaml
  src/Spice86/Views/MemoryView.axaml
  tests/Spice86.Tests/UI/Converters/AddressStringToLinearMemoryAddresssConverterTests.cs
Labels: UI

#1083 chore: update nugets
  src/Directory.Packages.props
Labels: 3rd party

#1084 refactor: INT21 warns when a program has exited
  src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs
Labels: DOS

#1081 Add Seer config file
  README.md
  doc/spice86.seer
Labels: enhancement

#1096 fix: Pass reference to functions dict
  src/Spice86/Spice86DependencyInjection.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
Labels: UI, bugfix

#1099 Fix: Lost Eden SB PCM and SB Music support
  src/Spice86.Core/Emulator/Devices/Sound/Blaster/HardwareMixer.cs
  src/Spice86.Core/Emulator/Devices/Sound/Blaster/SbType.cs
  src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlaster.cs
  src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlasterHardwareConfig.cs
  src/Spice86/Spice86DependencyInjection.cs
Labels: audio, compatibility, hardware, bugfix

#1109 fix: Don't crash with assert, throw instead
  src/Spice86.Core/Emulator/Devices/Video/VideoMemory.cs
Labels: bugfix

#1111 code microbenchmark template
  src/Directory.Packages.props
  src/Spice86.MicroBenchmarkTemplate/GlobalUsings.cs
  src/Spice86.MicroBenchmarkTemplate/Program.cs
  src/Spice86.MicroBenchmarkTemplate/Spice86.MicroBenchmarkTemplate.csproj
  src/Spice86.sln
Labels: performance

#1112 fix: No ViewModel update if we only show MainWindow
  src/Spice86/ViewModels/CpuViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MidiViewModel.cs
  src/Spice86/ViewModels/PaletteViewModel.cs
  src/Spice86/ViewModels/SoftwareMixerViewModel.cs
  src/Spice86/ViewModels/VideoCardViewModel.cs
  src/Spice86/Views/CpuView.axaml.cs
  src/Spice86/Views/MidiView.axaml.cs
  src/Spice86/Views/PaletteView.axaml.cs
  src/Spice86/Views/SoftwareMixerView.axaml.cs
  src/Spice86/Views/VideoCardView.axaml.cs
Labels: performance, refactoring

#1113 fix: Completely stop view update timers on visual tree detach
  src/Spice86/Infrastructure/DispatcherTimerStarter.cs
  src/Spice86/ViewModels/CpuViewModel.cs
  src/Spice86/ViewModels/IEmulatorObjectViewModel.cs
  src/Spice86/ViewModels/MidiViewModel.cs
  src/Spice86/ViewModels/PaletteViewModel.cs
  src/Spice86/ViewModels/SoftwareMixerViewModel.cs
  src/Spice86/ViewModels/VideoCardViewModel.cs
  src/Spice86/Views/CpuView.axaml.cs
  src/Spice86/Views/MidiView.axaml.cs
  src/Spice86/Views/PaletteView.axaml.cs
  src/Spice86/Views/SoftwareMixerView.axaml.cs
  src/Spice86/Views/VideoCardView.axaml.cs
Labels: performance
