Repository OpenRakis/Spice86, pull requests merged in 2025-04, with the labels that each got.

#1118 feat: All address textboxes have input validation
  src/Spice86/App.axaml.cs
  src/Spice86/Converters/AddressStringToLinearMemoryAddresssConverter.cs
  src/Spice86/Converters/SegmentedAddressConverter.cs
  src/Spice86/Infrastructure/StructureViewModelFactory.cs
  src/Spice86/Messages/AddViewModel.cs
  src/Spice86/Messages/AddressChangedMessage.cs
  src/Spice86/Messages/RemoveViewModelMessage.cs
  src/Spice86/Models/Debugging/LinearMemoryAddress.cs
  src/Spice86/Spice86DependencyInjection.cs
  src/Spice86/ViewLocator.cs
  src/Spice86/ViewModels/BreakpointRangeViewModel.cs
  src/Spice86/ViewModels/BreakpointViewModel.cs
  src/Spice86/ViewModels/BreakpointsViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/StackMemoryViewModel.cs
  src/Spice86/ViewModels/StructureViewModel.cs
  src/Spice86/ViewModels/ViewModelBase.cs
  src/Spice86/ViewModels/ViewModelWithErrorDialog.cs
  src/Spice86/Views/BreakpointsView.axaml
  src/Spice86/Views/DisassemblyView.axaml
  src/Spice86/Views/MemoryView.axaml
  src/Spice86/Views/StructureView.axaml
  src/Spice86/Views/StructureView.axaml.cs
  tests/Spice86.Tests/UI/Converters/AddressStringToLinearMemoryAddresssConverterTests.cs
Labels: enhancement, UI, refactoring

#1134 adds small native DOS test examples for partially missing DOS APIs
  tests/Spice86.Tests/Resources/NativeDosTests/build.bat
  tests/Spice86.Tests/Resources/NativeDosTests/c_exec.c
  tests/Spice86.Tests/Resources/NativeDosTests/clean.bat
  tests/Spice86.Tests/Resources/NativeDosTests/exec.asm
  tests/Spice86.Tests/Resources/NativeDosTests/hello.asm
  tests/Spice86.Tests/Resources/NativeDosTests/readme.md
  tests/Spice86.Tests/Resources/NativeDosTests/tsr.asm
Labels: DOS, 16 bit

#1133 hotfix: Valdiation does not block fields updates. Plus: Memory addressable limit validation (limit is A20Gate.EndOfHighMemoryArea), MemoryEdit/MemoryEditAddress validation, simplified all CanExecute methods
  src/Spice86.Core/Emulator/Memory/Memory.cs
  src/Spice86/ViewModels/BreakpointsViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/StructureViewModel.cs
  src/Spice86/ViewModels/ViewModelBase.cs
  src/Spice86/Views/MemoryView.axaml.cs
Labels: UI, bugfix

#1136 Fix/last minor validation errors on default values
  src/Spice86/Converters/HexadecimalStringToNumberConverter.cs
  src/Spice86/ViewModels/BreakpointsViewModel.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/ViewModelBase.cs
  src/Spice86/Views/BreakpointsView.axaml
Labels: UI, bugfix
