Repository OpenRakis/Spice86, pull requests merged in 2025-05, with the labels that each got.

#1135 New debugger
  .gitignore
  src/Spice86.Core/Emulator/VM/PauseHandler.cs
  src/Spice86/Behaviors/DisassemblyScrollBehavior.cs
  src/Spice86/Behaviors/HighlightBehavior.cs
  src/Spice86/Behaviors/InstructionPointerBehavior.cs
  src/Spice86/Behaviors/UseParentListBoxContextMenuBehavior.cs
  src/Spice86/Converters/BoolToBrushConverter.cs
  src/Spice86/Converters/BoolToFontWeightConverter.cs
  src/Spice86/Converters/BreakpointColorConverter.cs
  src/Spice86/Converters/BreakpointToBrushConverter.cs
  src/Spice86/Converters/ConverterUtilities.cs
  src/Spice86/Converters/FormattedTextSegmentsConverter.cs
  src/Spice86/Converters/FormatterTextKindToBrushConverter.cs
  src/Spice86/Converters/HighlightingConverter.cs
  src/Spice86/Converters/InstructionToStringConverter.cs
  src/Spice86/Converters/SegmentedAddressConverter.cs
  src/Spice86/Infrastructure/UIDispatcher.cs
  src/Spice86/MemoryWrappers/CodeMemoryStream.cs
  src/Spice86/MemoryWrappers/InstructionsDecoder.cs
  src/Spice86/Models/Debugging/CpuInstructionInfo.cs
  src/Spice86/Models/Debugging/EnrichedInstruction.cs
  src/Spice86/Spice86DependencyInjection.cs
  src/Spice86/Styles/DisassemblyResources.axaml
  src/Spice86/ViewModels/BreakpointViewModel.cs
  src/Spice86/ViewModels/BreakpointsViewModel.cs
  src/Spice86/ViewModels/DebuggerLineViewModel.cs
  src/Spice86/ViewModels/DisassemblyViewModel.Commands.cs
  src/Spice86/ViewModels/DisassemblyViewModel.cs
  src/Spice86/ViewModels/FlagViewModel.cs
  src/Spice86/ViewModels/FormattedTextSegment.cs
  src/Spice86/ViewModels/FormattedTextSegmentsOutput.cs
  src/Spice86/ViewModels/IDisassemblyCommands.cs
  src/Spice86/ViewModels/IDisassemblyViewModel.cs
  src/Spice86/ViewModels/IRegistersViewModel.cs
  src/Spice86/ViewModels/MemoryViewModel.cs
  src/Spice86/ViewModels/RegisterViewModel.cs
  src/Spice86/ViewModels/RegistersViewModel.cs
  src/Spice86/Views/DebugWindow.axaml
  src/Spice86/Views/DisassemblyView.axaml
  src/Spice86/Views/DisassemblyView.axaml.cs
  src/Spice86/Views/RegistersView.axaml
  src/Spice86/Views/RegistersView.axaml.cs
Labels: enhancement, UI, Debugger

#1165 Refactor/startup
  src/Spice86.Core/Emulator/ProgramExecutor.cs
  src/Spice86/App.axaml
  src/Spice86/App.axaml.cs
  src/Spice86/Behaviors/ShowInternalDebuggerBehavior.cs
  src/Spice86/Program.cs
  src/Spice86/Spice86DependencyInjection.cs
  src/Spice86/ViewModels/MainWindowViewModel.cs
  src/Spice86/ViewModels/PaletteViewModel.cs
  src/Spice86/ViewModels/SplashWindowViewModel.cs
  src/Spice86/Views/DebugWindow.axaml
  src/Spice86/Views/DisassemblyView.axaml
  src/Spice86/Views/MainWindow.axaml.cs
  src/Spice86/Views/SplashWindow.axaml
  src/Spice86/Views/SplashWindow.axaml.cs
  src/Spice86/Views/StructureView.axaml
  tests/Spice86.Tests/Spice86Creator.cs
Labels: UI, performance

#1176 fix: UI frozen because of async (again)
  src/Spice86/App.axaml.cs
  src/Spice86/ViewModels/SplashWindowViewModel.cs
  src/Spice86/Views/SplashWindow.axaml
Labels: UI, bugfix
